# Generated by Django 5.1.1 on 2024-09-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedinprofile',
            name='linkedin_access_token',
        ),
        migrations.RemoveField(
            model_name='linkedinprofile',
            name='linkedin_refresh_token',
        ),
        migrations.RemoveField(
            model_name='linkedinprofile',
            name='token_expires_at',
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='access_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='linkedin_uid',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
